#
# Add comment.
#

uint64 acu_can_timestamp	# can timestamp on acu

float32 voltage			# measured battery voltage [V]
float32 current			# measured battery current [A]

float32 percentage		# remaining percentage of battery [%]		

# TOPICS arm_control_unit_power_status left_arm_control_unit_power_status right_arm_control_unit_power_status back_arm_control_unit_power_status front_arm_control_unit_power_status
