#
# Add comment.
#
bool armed		# true if armed

bool x_ctrl		# if true position controller for x axis is on
bool y_ctrl		# if true position controller for y axis is on
bool z_ctrl		# if true position controller for y axis is on

bool vx_ctrl	# if true velocity controller for x axis is on 
bool vy_ctrl	# if true velocity controller for y axis is on 
bool vz_ctrl	# if true velocity controller for z axis is on 

bool yaw_ctrl	# if true yaw controller is on
bool vyaw_ctrl	# if true yaw velocity controller is on

# TOPICS controllers_switch mcu_controllers_switch ctrl_sm_controllers_switch